apiVersion: apps/v1
kind: Deployment
metadata:
  name: memtest-core-morebigger
spec:
  selector:
    matchLabels:
      app: memtest-core-morebigger
  template:
    metadata:
      labels:
        app: memtest-core-morebigger
    spec:
      containers:
        - image: stevegriffith/memtest:core
          imagePullPolicy: Always
          name: memtest-core-morebigger
          resources:
            limits:
              memory: "50Mi"
      nodeSelector:
        agentpool: winbig
      restartPolicy: Always
